# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-06 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem',
            field=models.TextField(),
        ),
    ]
