# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-06 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20151106_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='cartelisands',
            field=models.ManyToManyField(blank=True, to='cartelisands.Cartelisand'),
        ),
    ]
